safe: false
source: .
destination: ./_site
plugins_dir: ./_plugin
highlighter: rouge
markdown: kramdown
exclude: ['CNAME', 'Gemfile', 'Gemfile.lock', 'Rakefile', 'README.md', '.sass-cache', '_data/google-id.json']
sass:
  style: uncompressed
kramdown:
  toc_levels: "2,3"

plugins:
  - jekyll-assets
  
url: https://users.cs.fiu.edu
baseurl: /~afanasyev/classes/fall20/CNT-4713

# Configuration for permalink
permalink: /:title.html

# Configuration for site
title: "CNT-4713: Net Centric Computing (Computer Network Fundamentals) - Fall 2020 (FIU)"
description:
author: Alex Afanasyev
email:

spreadsheets:
  google_client_id: _data/google-id.json
  spreadsheet:
    - "1H5MPzX1PD4xkJ0AI0mMDqueAOtfZRH02fhnWPPW2q7Y"
  
# Configuration for navbar.html
navbar_list:
- name: Home
  link: /
- name: Due Dates
  link: /syllabus.html
- name: Weekly Schedule
  link: /schedule.html
- name: Homeworks
  link: /homeworks.html
- name: Project 1 (Accio)
  link: /project-1.html
- name: Project 2 (Confundo)
  link: /project-2.html
- name: Project 3 (Riddikulus)
  link: /project-3.html

course_info:
  times: 
  room: 
  name: Alex Afanasyev
  contact: aa at cs.fiu.edu
  office_hours: by appointment

  homeworks:
    - deadline: Week 2
    - deadline: Week 3
    - deadline: Week 5
    - deadline: Week 6
    - deadline: Week 8
    - deadline: Week 11
    - deadline: Week 13
    - deadline: Week 15

  midterm: Week 9

  final: Week 16
  final_room: 

  projects:
    - deadline: Week 5
    - deadline: Week 8
    - deadline: Week 15

assets:
  sources:
    - _assets/css
    - _assets/images
    - _assets/fonts
    - _assets/js
    - _assets/bower
    - _assets/misc

  plugins:
    css:
      autoprefixer:
        browsers:
          - "last 2 versions"
          - "IE > 9"

    img: { optim: {}, magick: {} }
