safe: false
source: .
destination: ./_site
highlighter: rouge
markdown: kramdown
exclude: ['CNAME', 'Gemfile', 'Gemfile.lock', 'Rakefile', 'README.md', '.sass-cache']
sass:
  style: uncompressed
kramdown:
  toc_levels: "2,3"

url: https://users.cs.fiu.edu
baseurl: /~afanasyev/classes/fall19/CNT-4713

# Configuration for permalink
permalink: /:title.html

# Configuration for site
title: "CNT-4713: Net Centric Computing (Computer Network Fundamentals) - Fall 2019 (FIU)"
description:
author: Alex Afanasyev
email:

# Configuration for navbar.html
navbar_list:
- name: Home
  link: /
- name: Syllabus
  link: /syllabus.html
- name: Homeworks
  link: /homeworks.html
- name: Project 1 (Accio)
  link: /project-1.html
- name: Project 2 (Confundo)
  link: /project-2.html
- name: Project 3 (Riddikulus)
  link: /project-3.html

course_info:
  times: 
  room: Online
  name: Alex Afanasyev
  contact: aa at cs.fiu.edu
  office_hours: by appointment

  homeworks_due: Wednesday of the week following the assignment, 11pm
  midterm: TBD

  final: TBD
  final_room: 

  projects:
    - deadline: TBD
    - deadline: TBD
    - deadline: TBD
