safe: false
source: .
destination: ./_site
highlighter: rouge
markdown: kramdown
exclude: ['CNAME', 'Gemfile', 'Gemfile.lock', 'Rakefile', 'README.md', '.sass-cache']
sass:
  style: uncompressed
kramdown:
  toc_levels: "2,3"

url: https://users.cs.fiu.edu
baseurl: /~afanasyev/classes/fall19/CNT-4713

# Configuration for permalink
permalink: /:title.html

# Configuration for site
title: "CNT-4713: Net Centric Computing (Computer Network Fundamentals) - Fall 2019 (FIU)"
description:
author: Alex Afanasyev
email:

# Configuration for navbar.html
navbar_list:
- name: Home
  link: /
- name: Syllabus
  link: /syllabus.html
- name: Homeworks
  link: /homeworks.html
- name: Project 1 (Accio)
  link: /project-1.html
- name: Project 2 (Confundo)
  link: /project-2.html
- name: Project 3 (Riddikulus)
  link: /project-3.html

course_info:
  times: 
  room: 
  name: Alex Afanasyev
  contact: aa at cs.fiu.edu
  office_hours: by appointment

  homeworks:
    - deadline: Week 2
    - deadline: Week 3
    - deadline: Week 5
    - deadline: Week 6
    - deadline: Week 8
    - deadline: Week 11
    - deadline: Week 13
    - deadline: Week 15

  midterm: Week 16

  final: Week 16
  final_room: 

  projects:
    - deadline: Week 5 (Sep 29, 2019)
    - deadline: Week 10 (Nov 2, 2019)
    - deadline: Week 15 (Dec 7, 2019)
